export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_CURRENT_WORDS_LIST = 'SET_CURRENT_WORDS__LIST'

export const SET_SEQUENCE_WORDS_LIST = 'SET_SEQUENCE_WORDS_LIST'

export const SET_TYPE_WORDS_LIST = 'SET_TYPE_WORDS_LIST'
